name: ModuleDemo
attributes:
  ORGANIZATIONNAME: ModuleDemo
options:
  bundleIdPrefix: com.module.demo
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "13.0"
targets:
  ModuleDemo:
    type: application
    platform: iOS
    attributes:
      ProvisioningStyle: Automatic
    sources:
      - App/Sources
    settings:
      INFOPLIST_FILE: "App/Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: "com.module.app"
    dependencies:
      - target: Cash
      - target: CashInterface
      - target: Investing
      - target: InvestingInterface
      - target: History
      - target: HistoryInterface
      - target: Context
      - target: UI
      - target: Utils
  ModuleDemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - App/Tests
    dependencies:
      - target: ModuleDemo

  # Core Targets

  Context:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: "Core/Context/Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: com.module.Context
    sources:
      - "Core/Context/Sources"

  UI:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: "Core/UI/Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: com.module.UI
    sources:
      - "Core/UI/Sources"
    dependencies:
      - target: Utils

  Utils:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: "Core/Utils/Sources/Info.plist"
      PRODUCT_BUNDLE_IDENTIFIER: com.module.Utils
    sources:
      - "Core/Utils/Sources"

  # Feature Targes

  Investing:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.investing
    sources:
      - Features/Investing/Sources
    dependencies:
      - target: HistoryInterface
      - target: InvestingInterface
      - target: UI
      - target: Utils

  InvestingInterface:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.InvestingInterface
    sources:
      - Features/Investing/Interface
    dependencies:
      - target: Context
      - target: UI
  
  Cash:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.Cash
    sources:
      - Features/Cash/Sources
    dependencies:
      - target: CashInterface
      - target: HistoryInterface
      - target: UI
      - target: Utils

  CashInterface:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.CashInterface
    sources:
      - Features/Cash/Interface
    dependencies:
      - target: Context
      - target: UI

  History:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.History
    sources:
      - Features/History/Sources
    dependencies:
      - target: CashInterface
      - target: InvestingInterface
      - target: HistoryInterface
      - target: UI
      - target: Utils

  HistoryInterface:
    type: library.static
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.module.HistoryInterface
    sources:
      - Features/History/Interface
    dependencies:
      - target: Context
      - target: UI
      
